import { Autocomplete, Box, Button, FormControl, MenuItem, OutlinedInput, Select, styled, TextField, Typography, Zoom } from '@mui/material'
import { useSnackbar } from 'notistack'
import React from 'react'
import { useSelector } from 'react-redux'
import { useNavigate } from 'react-router-dom'
import { publicRequest, userRequest } from '../../../requestMethods'
// import "./block2.css"
const Input = styled("input")(({ theme }) => ({
  width: "48%",
  height: "50px",
  border: "none",
  fontSize: "16px",
  borderRadius: "8px",
  paddingLeft: "16px",
  fontWeight: "500",
  color: "#676E8B",
  "&::placeholder": {
    fontStyle: "italic",
    fontWeight: "500",
    color: "#676E8B",
  },
  "&:focus": {
    outline: "none",
    border: "none"
  },
  [theme.breakpoints.down("sm")]: {
    width: "90%"
  }

}))
const Input1 = styled("input")(({ theme }) => ({
  width: "80%",
  height: "50px",
  border: "none",
  fontWeight: "500",
  borderRadius: "8px",
  fontSize: "16px",
  paddingLeft: "16px",
  color: "#676E8B",
  "&::placeholder": {
    fontStyle: "italic",
    fontWeight: "500",
    color: "#676E8B",
  },
  "&:focus": {
    outline: "none",
    border: "none"
  },
  [theme.breakpoints.down("sm")]: {
    width: "90%"
  }

}))
const Button1 = styled("button")(({ theme }) => ({
  border: "none",
  width: "200px",
  height: "50px",
  fontSize: "16px",
  display: "flex",
  justifyContent: "center",
  fontFamily: "Roboto",
  alignItems: "center",
  background: "teal",
  color: "white",
  cursor: "pointer",
  "&:hover": {
    letterSpacing: "1.5px",
    transition: "all 0.3s linear",
    background: "#eee",
    color: "teal",
    fontWeight: "600"
  },
  [theme.breakpoints.down("sm")]: {
    width: "90%"
  }
}))
const Form = styled("form")(({theme})=>({

}))

const category  = [
  { title: 'Academic' },
  { title: 'Accessories' },
  { title: 'IT Consulting' },
  { title: 'Academy' },
  { title: 'Accounting'},
  { title: "Administration" },
  { title: 'Accomodation' },
  {
    title: 'Adventure'
  },
  { title: 'Advertising' },
  { title:'Aesthetic' },
  {
    title: 'Agency',
  },
  {
    title: 'Agriculture'
  },
  { title: 'Air Conditioning' },
  { title: 'Airline' },
  {
    title:'Alcohol',
  },
  { title: 'Amazon' },
  { title: 'Analytics' },
  { title: 'Animal Rescue' },
  {
    title: 'Animals'
  },
  { title: 'Animation' },
  { title: 'Apartment' },
  { title: 'App' },
  { title: 'Apparel'},
  { title: 'Application'},
  { title: 'Architecture' },
  { title: 'Aromatherpy' },
  { title: 'Art' },
  { title: 'Artificial Intelligence' },
  { title: 'Arts And Crafts' },
  { title: 'Association' },
  { title: 'Astrology'},
  { title: 'Athletic Wear' },
  { title: 'Attorney'},
  { title: 'Audio' },
  { title: 'Author' },
  { title: 'Auto' },
  { title: 'Auto Detailing' },
  { title: 'Automation' },
  { title: 'Automotive' },
  { title: 'Aviation' },
  { title: 'Baby' },
  { title: 'Baby Clothing' },
  { title: 'Baby Shop' },
  { title: 'Bag Shop'},
  { title: 'Bags'},
  { title: 'Bakery' },
  { title: 'Band' },
  { title: 'Banking' },
  { title: 'Bar' },
  { title: 'Barber' },
  { title: 'Baseball'},
  {
    title: 'Basketball',
  },
  { title: 'Bath Bombs' },
  { title: 'Beauty' },
  { title: 'Beverage'},
  { title: 'Brand' },
  { title: 'Boat' },
  { title: 'Bracelets' },
  { title: 'The Shining', year: 1980 },
  { title: 'Business Coach' },
  { title: 'Cabinet Maker'},
  { title: 'Cafe' },
  { title: 'Cakes' },
  { title: 'Campaign' },
  { title: 'Camping' },
  { title: 'Candles' },
  { title: 'Candy'},
  { title: 'Cannbis' },
  { title: 'Car Club'},
  { title: 'Car Rental' },
  {
    title: 'Car Sales'
  },
  { title: 'Car Sales' },
  { title: 'Car Wash'},
  { title: 'Cards' },
  { title: 'Care' },
  { title: 'Carpentry' },
  { title: 'Carpet Cleaning'},
  { title: 'Cars' },
  { title: 'Carwash'},
  { title: 'Catering' },
  { title: 'Cattle' },
  {
    title: 'Charity',
  },
  { title: 'Chemical' },
  { title: 'Childcare' },
  { title: 'Chiroractic' },
  { title: 'Chocolate' },
  { title: 'Christian blog' },
  { title: 'Cinema' },
  { title: 'Cleaning' },
  { title: 'Clothing And Accessories' },
  { title: 'Clothing Brand'},
  { title: 'Coach' },
  { title:'Coaching Brand'},
  { title: 'Coffee Roaster' },
  { title: 'Communications' },
  { title: 'Contracting' },
  { title: 'Coworking Space' },
  { title: 'Creative'},
  { title: 'Cupcakes'},
  { title: 'Dance'},
  { title: 'Dancer'},
  { title: 'Data'},
  { title: 'Dating'},
  { title: 'Daycare'},
  { title: 'Decoration'},
  { title: 'Dental'},
  { title: 'Design Agency'},
  { title: 'Detailing'},
  { title: 'Diamond'},
  { title: 'Digital Agency'},
  { title: 'Digital Marketing'},
  { title: 'Dog Training'},
  { title: 'Dog Treats'},
  { title: 'Dog Walking'},
  { title: 'Education'},
  { title: 'Environmental Organization'},
  { title: 'Escape Room'},
  { title: 'Essential Oils'},
  { title: 'Event Management'},
  { title: 'Event Planning'},
  { title: 'Executive Coaching'},
  { title: 'Eyelashes'},
  { title: 'Factory'},
  { title: 'Family'},
  { title: 'Farming'},
  { title: 'Farming'},
  { title: 'Fashion And Beauty'},
  { title: 'Fast Food Restaurant'},
  { title: 'Festival'},
  { title: 'Finance'},
  { title: 'Financial'},
  { title: 'Fitness Services'},
  { title: 'Fitness Apparel'},
  { title: 'Food Catering'},
  { title: 'Football'},
  { title: 'Football Club'},
  { title: 'Footwear'},
  { title: 'Football Team'},
  { title: 'Freelance'},
  { title: 'Foundation'},
  { title: 'Gadget Shop'},
  { title: 'Gadgets'},
  { title: 'Gambling'},
  { title: 'Gamer'},
  { title: 'Games'},
  { title: 'Gaming'},
  { title: 'Gaming Channel'},
  { title: 'Gaming Team'},
  { title: 'Garage'},
  { title: 'Gardening'},
  { title: 'General Contractor'},
  { title: 'General Merchandise'},
  { title: 'General Store'},
  { title: 'General Trading'},
  { title: 'Graphic Design'},
  { title: 'Graphic Designer'},
  { title: 'Hair'},
  { title: 'Hair Accessories'},
   { title: 'Hair And Beauty'},
   { title: 'Hair Extensions'},
   { title: 'Hair Salon'},
   { title: 'Handcrafts'},
   { title: 'Hairdresser'},
   { title: 'Handmade Crafts'},
   { title: 'Handmade Jewellery'},
   { title: 'Handmade Soap'},
   { title: 'Handyman'},
   { title: 'Healing'},
   { title: 'Health'},
   { title: 'Health And Beauty'},
   { title: 'Health And Fitness'},
   { title: 'Health And Wellness'},
   { title: 'Health Care'},
   { title: 'Health Coach'},
   { title: 'Healthy Food'},
   { title: 'Heating'},
   { title: 'Home Care'},
   { title: 'Home Staging'},
   { title: 'Homeware'},
   { title: 'Hospitality'},
   { title: 'House Clening'},
   { title: 'Human Resources'},
   { title: 'HVAC'},
   { title: 'Hypnotherapy'},
   { title: 'Ice Cream'},
   { title: 'Ice Cream Shop'},
   { title: 'Industrial'},
   { title: 'Information Technology'},
   { title: 'Innovation'},
   { title: 'Instagram'},
   { title: 'Insulation'},
   { title: 'Insurance'},
   { title: 'Janitorial'},
   { title: 'Journalism'},
   { title: 'Junk Removal'},
   { title: 'Laboratory'},
   { title: 'Landscaping'},
   { title: 'Lashes'},
   { title: 'Laundry'},
   { title: 'Law'},
   { title: 'Lawn Care'},
   { title: 'Learning'},
   { title: 'Legal'},
   { title: 'Lemonade Stand'},
   { title: 'Life Coaching'},
   { title: 'Magazine'},
   { title: 'Maintenance'},
   { title: 'Magic'},
   { title: 'Makeup'},
   { title: 'Makeup Artist'},
   { title: 'Management'},
   { title: 'Management Consulting'},
   { title: 'Manufacturing'},
   { title: 'Marijuana'},
   { title: 'Marine'},
   { title: 'Market'},
   { title: 'Marketing'},
   { title: 'Marketing Digital'},
   { title: 'Marketplace'},
   { title: 'Martial Arts'},
    { title: 'Message'},
    { title: 'Message Therapy'},
    { title: 'Mechanic'},
    { title: 'Mechanical'},
    { title: 'Media'},
    { title: 'Mediation'},
    { title: 'Medical'},
    { title: 'Meditation'},
    { title: 'Medical Marijuana'},
    { title: "Men's Fashion"},
    { title: 'Mental Health'},
    { title: 'Merchandise'},
    { title: 'Military'},
    { title: 'Mobile Application'},
    { title: 'Mortgage'},
    { title: 'Mortgage Broker'},
    { title: 'Motivation'},
    { title: 'Music Band'},
    { title: 'Music Label'},
    { title: 'Musician'},
    { title: 'Nail Technician'},
    { title: 'Nails'},
    { title: 'Natural Cosmetics'},
    { title: 'Nature'},
    { title: 'Network Marketing'},
    { title: 'New Reality'},
    { title: 'Oil And Gas'},
    { title: 'Onilne Marketing'},
    { title: 'Online Retail'},
    { title: 'Online Sales'},
    { title: 'Optical'},
    { title: 'Organic'},
    { title: 'Organic Food'},
    { title: 'Organization'},
    { title: 'Paint'},
    { title: 'Painting'},
    { title: 'Pastry Shop'},
    { title: 'Patisserie'},
    { title: 'Personal Blog'},
    { title: 'Personal Brand'},
    { title: 'Party'},
    { title: 'Personal Development'},
    { title: 'Pharmacy'},
    { title: 'Phone Cases'},
    { title: 'Pet Care'},
    { title: 'Photography'},
    { title: 'Photography And Video'},
    { title: 'Physical Therapy'},
    { title: 'Physiotherapy'},
    { title: 'Pilates'},
    { title: 'Plants'},
    { title: 'Plastering'},
    { title: 'Podcast'},
    { title: 'Political Party'},
    { title: 'Professional Organizer'},
    { title: 'Political Management'},
    { title: 'Psychotherapy'},
    { title: 'Public Relations'},
    { title: 'Ranch'},
    { title: 'Radio'},
    { title: 'Racing'},
    { title: 'Rapper'},
    { title: 'Real Estate'},
    { title: 'Real Estate Investing'},
    { title: 'Realtor'},
    { title: 'Rental'},
    { title: 'Record Label'},
    { title: 'Recuitment Agency'},
    { title: 'Renewable Energy'},
    { title: 'Research'},
    { title: 'Restaurant'},
    { title: 'Retail'},
    { title: 'Rock Band'},
    { title: 'Salon'},
    { title: 'Sailing'},
    { title: 'Sandwich Shop'},
    { title: 'Shoe Brand'},
    { title: 'Skate Shop'},
    { title: 'Skin Care'},
    { title: 'Snacks'},
    { title: 'Sneakers'},
    { title: 'Soap Shop'},
    { title: 'Soaps'},
    { title: 'Social Media'},
    { title: 'Social Media Marketing'},
    { title: 'Software'},
    { title: 'Solar Energy'},
    { title: 'Spa'},
    { title: 'Spa Products'},
    { title: 'Space'},
    { title: 'Spiritual'},
    { title: 'Sports And Recreation Education'},
    { title: 'Sports Media '},
    { title: 'Sportswear'},
    { title: 'Staffing'},
    { title: 'Startup'},
    { title: 'Stationary'},
    { title: 'Storage'},
    { title: 'Straming'},
    { title: 'Storage'},
    { title: 'Street Wear'},
    { title: 'Sunglasses'},
    { title: 'Sustainability'},
    { title: 'Swimwear'},
    { title: 'Tailor'},
    { title: 'Talk Show'},
    { title: 'Tanning'},
    { title: 'Tarot'},
    { title: 'Tattoo'},
    { title: 'Tax Preparation'},
    { title: 'Taxi'},
    { title: 'Tea'},
    { title: 'Tea Shop'},
    { title: 'Teacher'},
    { title: 'Teaching'},
    { title: 'Team'},
    { title: 'Telecommunications'},
    { title: 'Theatre'},
    { title: 'Therapy'},
    { title: 'Tour Operator'},
    { title: 'Trade'},
    { title: 'Trading'},
    { title: 'Training'},
    { title: 'Travel'},
    { title: 'Travel Agency'},
    { title: 'Translation'},
    { title: 'Transportation'},
    { title: 'Travel'},
    { title: 'Travel Agency'},
    { title: 'Travel Blog'},
    { title: 'Vacation Rental'},
    { title: 'Vape Shop'},
    { title: 'Vegan Shop'},
    { title: 'Underwear'},
    { title: 'TV Channel'},
    { title: 'Twitch Streamer'},
    { title: 'Venture Capital '},
    { title: 'Veterinary'},
    { title: 'Video Games'},
    { title: 'Videography'},
    { title: 'vintage'},
    { title: 'Virtual Assitant'},
    { title: 'Virtual Reality'},
    { title: 'Watch Shop'},
    { title: 'Watches'},
    { title: 'Water'},
    { title: 'Water Filter'},
    { title: 'Wedding Photography'},
    { title: 'Wholesale'},
    { title: 'Window Cleaning'},
    { title: 'Yoga'},
    { title: 'Yoga Studio'},
    { title: 'Youtube channel'},
    { title: 'Youtube Gaming'},
    { title: 'Butcher Shop'},
    { title: 'Clothing Shop'},
    { title: 'Coffee Shop'},
    { title: 'Flower Shop'},
    { title: 'Gift Shop'},
    { title: 'Ice Cream Shop'},
    { title: 'Pet Shop'},
    { title: 'Phone Shop'},
    { title: 'Pizza Shop'},
    { title: 'Sex Shop'},
    { title: 'Shop Online'},
    { title: 'Shopping'},
    { title: 'Sneakers Shop'},
    { title: 'Sports Shop'},
    { title: 'Toy Shop'},
    { title: 'Workshop'},
    { title: 'Construction'},
    { title: 'Business Consulting'},
    { title: 'Beer'},
    { title: 'Betting'},
    { title: 'Bikes'},
    { title: 'Bitcoin'},
    { title: 'Bookkeeping'},
    { title: 'Books'},
    { title: 'Blog'},
    { title: 'Boutique'},
    { title: 'Brewery'},
     { title: 'Builder'},
     { title: 'Building'},
     { title: 'Burger'},
     { title: 'CBD'},
     { title: 'CRM'},
     { title: 'CMS'},
     { title: 'Club'},
     { title: 'Cyber Security'},
     { title: 'Distribution'},
     { title: 'Dog Breeder'},
     { title: 'Embroidery'},
     { title: 'Food Blog'},
     { title: 'Jobs'},
     { title: 'Lifestyle Blog'},
     { title: 'Lightbox'},
     { title: 'Mobile'},
     { title: 'Mobile Shop'},
     { title: 'Night Club '},
     { title: 'Photo Booth'},
     { title: 'Plumber'},
     { title: 'Publishing'},
     { title: 'Soccer Club'},
     { title: 'Subscription Box'},
     { title: 'Web'},
     { title: 'Website'},
     { title: 'Wellbeing'},
     { title: 'Website'},
     { title: 'Web Design'},
     { title: 'Chef'},
     { title: 'Chicken'},
     { title: 'Children'},
     { title: 'Church'},
     { title: 'City'},
     { title: 'Clinic'},
     { title: 'Cleaning'},
     { title: 'Cloud'},
     { title: 'Coffee Roaster'},
     { title: 'Comedy'},
     { title: 'College'},
     { title: 'Commerce'},
     { title: 'Community'},
     { title: 'Computer'},
     { title: 'Concrete'},
     { title: 'Conference'},
     { title: 'Cookies'},
     { title: 'Copywriting'},
     { title: 'Cosmetics'},
     { title: 'Counselling'},
     { title: 'Cooking'},
     { title: 'Courier'},
     { title: 'Coworking Space'},
     { title: 'Crochet'},
     { title: 'Crossfit'},
     { title: 'Cryptocurrency'},
     { title: 'Decor'},
     { title: 'Ecology'},
     { title: 'eCommerce'},
     { title: 'Fencing'},
     { title: 'Fintech'},
     { title: 'Food Truck'},
     { title: 'Gym Clothing'},
     { title: 'Hockey'},
     { title: 'Holistic'},
     { title: 'Home Inspection'},
     { title: 'ICT'},
     { title: 'Juice'},
     { title: 'Kids Clothing'},
     { title: 'Lipsstick'},
     { title: 'Locksmith'},
     { title: 'Logistics'},
     { title: 'Medicine'},
     { title: 'Motocross'},
     { title: 'Music Producer'},
     { title: 'Office'},
     { title: 'Pest Control'},
     { title: 'Phone Cases'},
     { title: 'Politics'},
     { title: 'Producer'},
     { title: 'Psycology'},
     { title: 'Recipes'},
     { title: 'Recuiting'},
     { title: 'Recycling'},
     { title: 'School'},
     { title: 'Science'},
     { title: 'School Project'},
     { title: 'Services'},
     { title: 'Soccer'},
     { title: 'Society'},
     { title: 'Socks'},
     { title: 'Trucking'},
     { title: 'Voice Over'},
     { title: 'Biotech'},
     { title: 'Delivery'},
     { title: 'Desserts'},
     { title: 'Developer'},
     { title: 'Development'},
     { title: 'Diet'},
     { title: 'Drone'},
     { title: 'Electrical'},
     { title: 'Equine'},
     { title: 'Engineering'},
     { title: 'Export'},
     { title: 'Government'},
     { title: 'Hedge Fund'},
     { title: 'Hemp'},
     { title: 'Horses'},
     { title: 'Hotel'},
     { title: 'Honey'},
     { title: 'Import Export'},
     { title: 'Internet'},
     { title: 'Interior'},
     { title: 'Investment'},
     { title: 'Joinery'},
     { title: 'Junk Removal'},
     { title: 'Learning'},
     { title: 'Lending'},
     { title: 'Lingerie'},
     { title: 'Love'},
     { title: 'Money'},
     { title: 'Movie'},
     { title: 'Network'},
     { title: 'News'},
     { title: 'Olive Oil'},
     { title: 'Online Store'},
     { title: 'People'},
     { title: 'Perfume'},
     { title: 'Pet Sitting'},
     { title: 'Poetry'},
     { title: 'Product Design'},
     { title: 'Property'},
     { title: 'Religion'},
     { title: 'Remodelling'},
     { title: 'Selling'},
     { title: 'Sewing'},
     { title: 'Sex Toys'},
     { title: 'Shoes'},
     { title: 'Shoe Shop'},
     { title: 'Singer'},
     { title: 'Slime'},
     { title: 'Smoke Shop'},
     { title: 'Steel'},
     { title: 'Teeth Whitening'},
     { title: 'Tennis'},
     { title: 'Test'},
     { title: 'Tile'},
     { title: 'Tour Operator'},
     { title: 'University'},
     { title: 'Vending'},
     { title: 'Videos'},
     { title: 'Weed'},
     { title: 'Welding'},
     { title: 'Weight Loss'},
     { title: 'Wellbeing'},
     { title: 'Wellness'},
     { title: 'Wine'},
     { title: 'Writer'},
     { title: '3D Printing'},
     { title: 'Advertising'},
     { title: 'Aesthetics'},
     { title: 'Dog Grooming'},
     { title: 'Drink'},
     { title: 'Film'},
     { title: 'Fish'},
     { title: 'Florist'},
     { title: 'Flooring'},
     { title: 'Fruits'},
     { title: 'Furniture'},
     { title: 'Hair Stylist'},
     { title: 'Home Improvement'},
     { title: 'IT'},
     { title: 'Internet'},
     { title: 'Knitting'},
     { title: 'Nursing'},
     { title: 'Nutrition'},
     { title: 'Oil'},
     { title: 'Photo Studio'},
     { title: 'Production'},
     { title: 'Shirts'},
     { title: 'T shirt'},
     { title: 'Textile'},
     { title: 'Tiling'},
     { title: 'Golf'},
    
    
    
   
  

];


const initialValues = {
  companyName: "",
  category:"",
  slogan:""
};


const Block2 = () => {
  let users = useSelector((state) => state.user ? state.user : "")
  console.log(users)
  // const Token  = users===null ? "" : users.currentUser.data.token
  const [logoData, setLogoData] = React.useState(initialValues);
  const {enqueueSnackbar} = useSnackbar();


  const navigate = useNavigate()

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setLogoData({
      ...logoData,
      [name]: value,
    });
    console.log(logoData)
  };
 

  const handleSubmit = () => {
    console.log(logoData)
    if (users.currentUser !== null) {
      const addLogo = async (logoData) => {
        const res = await userRequest.post("/logo/create", logoData)
        console.log(res)
        if(res.data?.status==="SUCCESS"){
          enqueueSnackbar('Thank you for confirming, our team contact you', {
            variant: 'success',
            anchorOrigin: {
              vertical: 'top',
              horizontal: 'center'
            },
            TransitionComponent: Zoom
            });
          }
          navigate('/')
          return res;
      }
      console.log("submit")
      addLogo(logoData);
    } else {
      navigate("/login")
    }

  }
  return (
    <Box sx={{ fontFamily: "Roboto" }} >
      <Box sx={{ display: "flex", margin: "40px 0px", justifyContent: "center", alignItems: "center", flexDirection: 'column', gap: "15px" }} >
        <Typography variant='h1' sx={{ fontFamily: "Roboto", fontSize: { md: "48px", sm: "40px", xs: "32px" }, color: "#090B17", fontWeight: "700", textAlign: "center" }}  >Make Your Own Beautiful <span style={{ color: "teal", fontStyle: "italic" }} >Brand</span> </Typography>
        <Typography variant='body' sx={{ fontFamily: "Roboto", fontSize: "20px", color: "#676E8B", fontWeight: "400", textAlign: "center", padding: "0px 10px" }} >Lorem ipsum dolor, sit amet consectetur adipisicing elit.</Typography>
      </Box>

      <Form sx={{ width: "100%", display: "flex", justifyContent: "center", alignItems: "center", flexDirection: 'column', gap: "20px" }} >

        <Box sx={{ display: "flex", alignItems: "center", width: { md: "50%", sm: "75%", xs: "95%" }, justifyContent: "space-between", gap: "10px", flexDirection: { sm: "row", xs: "column" } }} >

          <Input type="text" placeholder='Enter Your Company Name' required name='companyName' value={logoData.companyName} onChange={(e) =>handleInputChange(e)} />
          <FormControl sx={{ width: { sm: "48%", xs: "90%" }, background: "white", border: "none", outline: "none", "&:focus": { border: "1px solid teal", outline: "1px solid teal" } }}>
         
                <Autocomplete
                name='category'
                value={logoData.category} 
                onChange={(e, value) =>setLogoData({category:value})}
        options={category.map((option) => option.title)}
        renderInput={(params) => (
          <TextField
          required
          placeholder='Select Your category'
          sx={{"&::placeholder":{fontSize:"20px", fontWeight:"500"}, ".MuiInputBase-root::placeholder":{fontSize:"16px", fontWeight:"600", opacity:"1"}, fontSize:"16px", fontWeight:"500", "& input::placeholder":{fontSize:"16px", fontWeight:"500", color:"#333"},"& fieldset": { border: 'none' },"fieldset:focus":{border: "1px solid teal"}}}
            {...params}
            name="category"
            value={logoData.category} 
            InputProps={{
              ...params.InputProps,
              type: 'search',
            }}
          />
        )}
      />
          </FormControl>
        </Box>
        <Box sx={{ display: "flex", alignItems: "center", width: { md: "50%", sm: "75%", xs: "95%" }, justifyContent: "space-between", gap: "10px", flexDirection: { sm: 'row', xs: "column" } }}  >
          <Input1 type="text" placeholder='Enter Your Slogan (optional)' name="slogan" value={logoData.slogan} onChange={(e) =>handleInputChange(e)}  />
       { logoData.companyName==="" || logoData.category===null ?  <Button type='submit' variant='outlined'  disabled >Get Started</Button> : <Button1 type='submit' onClick={handleSubmit} >Get Started</Button1>  }

        </Box>
      </Form>
    </Box>
  )
}

export default Block2